package tubes.pbo.be.history.service;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import tubes.pbo.be.shared.config.FileStorageConfig;
import tubes.pbo.be.shared.exception.FileOperationException;
import tubes.pbo.be.shared.exception.ResourceNotFoundException;
import tubes.pbo.be.summary.model.Summary;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Service for handling file operations related to summaries.
 * Provides PDF generation and retrieval functionality.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class FileService {

    private final FileStorageConfig fileStorageConfig;

    /**
     * Generates a PDF document from the summary text.
     *
     * @param summary The summary containing the text to convert to PDF
     * @return byte array containing the generated PDF
     * @throws RuntimeException if PDF generation fails
     */
    public byte[] generateSummaryPdf(Summary summary) {
        log.info("Generating PDF for summary ID: {}", summary.getId());
        
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            // Initialize PDF writer and document
            PdfWriter writer = new PdfWriter(baos);
            PdfDocument pdfDocument = new PdfDocument(writer);
            Document document = new Document(pdfDocument);

            // Add title
            Paragraph title = new Paragraph("Summary of: " + summary.getOriginalFilename());
            title.setFontSize(16);
            document.add(title);
            
            document.add(new Paragraph("\n"));

            // Add summary text - split by paragraphs
            String[] paragraphs = summary.getSummaryText().split("\n\n");
            for (String para : paragraphs) {
                if (!para.trim().isEmpty()) {
                    document.add(new Paragraph(para.trim()));
                    document.add(new Paragraph("\n"));
                }
            }

            // Add metadata footer
            document.add(new Paragraph("\n"));
            document.add(new Paragraph("---").setFontSize(10));
            
            Paragraph provider = new Paragraph("Generated by: " + summary.getAiProvider() + " (" + summary.getAiModel() + ")");
            provider.setFontSize(8);
            document.add(provider);
            
            Paragraph date = new Paragraph("Date: " + summary.getCreatedAt().toString());
            date.setFontSize(8);
            document.add(date);

            // Close document
            document.close();

            log.info("Successfully generated PDF for summary ID: {}", summary.getId());
            return baos.toByteArray();
            
        } catch (Exception e) {
            log.error("Failed to generate PDF for summary ID: {}", summary.getId(), e);
            throw new FileOperationException("Failed to generate PDF: " + e.getMessage(), e);
        }
    }

    /**
     * Retrieves the original PDF file from storage.
     *
     * @param summary The summary containing the file path
     * @return byte array containing the original PDF file
     * @throws ResourceNotFoundException if the file is not found
     * @throws RuntimeException if file reading fails
     */
    public byte[] getOriginalPdf(Summary summary) {
        log.info("Retrieving original PDF for summary ID: {}", summary.getId());
        
        try {
            // Resolve the full path using the upload directory
            Path filePath = fileStorageConfig.getUploadPath().resolve(summary.getFilePath());
            File file = filePath.toFile();
            
            if (!file.exists()) {
                log.error("Original PDF file not found: {}", filePath.toAbsolutePath());
                throw new ResourceNotFoundException("Original PDF file not found");
            }

            byte[] fileContent = Files.readAllBytes(filePath);
            log.info("Successfully retrieved original PDF for summary ID: {}", summary.getId());
            return fileContent;
            
        } catch (IOException e) {
            log.error("Failed to read original PDF for summary ID: {}", summary.getId(), e);
            throw new FileOperationException("Failed to read PDF file: " + e.getMessage(), e);
        }
    }
}
